# -*- coding: utf-8 -*-
"""vrushali assignment string1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15G109zFwFI4KfW26_6USfnjm2rK-tYPK
"""



#1
# function to check string is
# palindrome or not
def isPalindrome(str):
 
    # Run loop from 0 to len/2
    for i in range(0, int(len(str)/2)):
        if str[i] != str[len(str)-i-1]:
            return False
    return True
 
# main function
s = "malayalam"
ans = isPalindrome(s)
 
if (ans):
    print("Yes")
else:
    print("No")

#3. WAP to remove all occurences of given char from String
def delete_all_occurrences(str1, ch):
     result = str1.replace(ch, "")
     return(result)

str_text = "Delete all occurrences of a specified character in a given string"
print("Original string:")
print(str_text)
print("\nModified string:")
ch='a'
print(delete_all_occurrences(str_text, ch))

#4. WAP to accept 2 string and check whether they are anagram or not eg) MARY ARMY
# function to check if two strings are
# anagram or not
def check(s1, s2):
     
    # the sorted strings are checked
    if((s1)== (s2)):
        print("The strings are anagrams.")
    else:
        print("The strings aren't anagrams.")        
         
s1 ="MARY"
s2 ="ARMY"
check(s1, s2)

#5.WAP to reverse each word in a sentence Python is fun -->nohtyP si nuf
# Python code to Reverse each word
# of a Sentence individually
 
# Function to Reverse words
def reverseWordSentence(Sentence):
 
    # Splitting the Sentence into list of words.
    words = Sentence.split(" ")
     
    
    newWords = [word[::-1] for word in words]
     
    # Joining the new list of words
    # to for a new Sentence
    newSentence = " ".join(newWords)
 
    return newSentence
 
#  Code
Sentence = "python is fun"

print(reverseWordSentence(Sentence))

#6. WAP program to find frequency of each character in given String
string = "happy Life"

for i in string:
    frequency = string.count(i)
    print(str(i) + ": " + str(frequency), end=", ")

#7. WAP to extract first alphabet from given sentence to form a new word
line = "I like to play guitar and piano and drums"
letters = ""
words = line.split()
for word in words:
    letters = letters + word[0]
print(" ".join(letters).upper())

#8. Star Pattern Programs
n=5
for i in range(n):
    for j in range(1,i+1):
        print("V",end="")
    print("\n")

#10. WAP to replace every character by its next subsequent character.
string=input("enter string:")
n_string=''.join(chr(ord(char)+1)for char in string)
print(n_string)

#11. write a Python program to count the number of characters (character frequency) ina string

n=input("enter string")
s={}
for i in n:
    if i in s:
        s[i]+=1
    else:
         s[i]=1
print("charactors frequency occurs count is:" + str(s))

# 12. Write a Python program to remove the characters which have odd index values of agiven string

user=input("enter string you want:")

def r_odd_cha(user):
    output= " "
    for i in range(len(user)):
        if i%2==0:
            output=output+user[i]
    return output
print(r_odd_cha(user))

# 13. Write a Python program to count the occurrences of each word in a given sentence.
user=input("enter sentence:")
dict_word=dict()
variable=user.split(" ")
for x in variable:
    if x in dict_word:
        dict_word[x]+=1
    else:	
        dict_word[x]=1
print(dict_word)

# 14. Write a Python program to swap cases or toggle cases of a given string.

string="happy birthday"            # in this problem if u have conversion UPPER TO LOWER
                                                                            # lower to upper      
print(string.swapcase())

